# Generated by Django 2.2 on 2019-10-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
