# Generated by Django 2.2 on 2019-08-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190828_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
