# Generated by Django 2.2 on 2019-10-18 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_codeforcoder',
            new_name='Contact',
        ),
    ]
