# Generated by Django 2.2 on 2019-10-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_registered_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered_players',
            name='game',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='registered_players',
            name='time',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='registered_players',
            name='date',
            field=models.CharField(default='', max_length=30),
        ),
    ]
