# Generated by Django 2.2 on 2019-10-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20191019_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered_players',
            name='status',
            field=models.CharField(default='', max_length=30),
        ),
    ]
