# Generated by Django 2.2 on 2019-10-23 10:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_registered_players_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Free',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=30, validators=[django.core.validators.MinLengthValidator(4)])),
                ('date', models.CharField(default='', max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Contact',
            },
        ),
    ]
