# Generated by Django 2.2 on 2019-10-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20191025_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='free',
            options={'verbose_name_plural': 'Free'},
        ),
        migrations.AlterField(
            model_name='free',
            name='check1',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='free',
            name='check2',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='free',
            name='check3',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='free',
            name='check4',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='free',
            name='check5',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='free',
            name='check6',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='free',
            name='check7',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
