# Generated by Django 2.2 on 2019-10-25 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20191025_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='free',
            name='date',
        ),
    ]
