# Generated by Django 2.2 on 2019-10-25 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_remove_free_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='free',
            old_name='check2',
            new_name='free_dates',
        ),
        migrations.RemoveField(
            model_name='free',
            name='check1',
        ),
        migrations.RemoveField(
            model_name='free',
            name='check3',
        ),
        migrations.RemoveField(
            model_name='free',
            name='check4',
        ),
        migrations.RemoveField(
            model_name='free',
            name='check5',
        ),
        migrations.RemoveField(
            model_name='free',
            name='check6',
        ),
        migrations.RemoveField(
            model_name='free',
            name='check7',
        ),
    ]
