# Generated by Django 2.2 on 2019-10-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20191025_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite_Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_from', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('invite_to', models.CharField(blank=True, default='', max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Invite Friend',
            },
        ),
    ]
