# Generated by Django 2.2 on 2019-10-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_invite_friend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_1', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('friend_2', models.CharField(blank=True, default='', max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Friends',
            },
        ),
    ]
