# Generated by Django 2.2 on 2019-10-28 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registered_players',
            name='status',
        ),
    ]
